//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace System.CommandLine.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CommandLineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface ICommandLineListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandLine([NotNull] CommandLineParser.CommandLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandLine([NotNull] CommandLineParser.CommandLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CommandLineParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CommandLineParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] CommandLineParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] CommandLineParser.ValueContext context);
}
} // namespace System.CommandLine.Parser
