
# The path to the ANTLR4 and Java Compiler executables
ANTLR4COMPILER          = java -Xmx500M -cp "/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH" org.antlr.v4.Tool
JAVACOMPILER            = javac

# The input and output files
INPUTFILES              = CommandLine.g4
JAVAOUTPUTFILES         = CommandLineBaseListener.java CommandLineLexer.java CommandLineListener.java CommandLineParser.java
JAVACOMPILEROUTPUTFILES = CommandLineBaseListener.class CommandLineLexer.class CommandLineListener.class CommandLineParser.class
CSHARPOUTPUTFILES       = CommandLineBaseListener.cs CommandLineLexer.cs CommandLineListener.cs CommandLineParser.cs

# The target that generates the Java as well as the C# version of the lexer and parser
All: CommandLineJava CommandLineCSharp

# The target that generates the Java version of the lexer and parser
CommandLineJava: $(JAVAOUTPUTFILES) $(JAVACOMPILEROUTPUTFILES)
$(JAVAOUTPUTFILES):
	$(ANTLR4COMPILER) $(INPUTFILES)
$(JAVACOMPILEROUTPUTFILES):
	$(JAVACOMPILER) *.java

# The target that generates the C# version of the lexer and parser
CommandLineCSharp: $(CSHARPOUTPUTFILES)
$(CSHARPOUTPUTFILES):
	$(ANTLR4COMPILER) $(INPUTFILES) -Dlanguage=CSharp -package System.CommandLine.Parser.Antlr

# The target that cleans up the environment by deleting all files generated by the build
Clean: CleanJava CleanCSharp
CleanJava:
	rm -f *.java *.class *.tokens
CleanCSharp:
	rm -f *.cs *.tokens