//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace System.CommandLine.Parser.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CommandLineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
internal interface ICommandLineListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandLine([NotNull] CommandLineParser.CommandLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandLine([NotNull] CommandLineParser.CommandLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WindowsStyleSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindowsStyleSwitch([NotNull] CommandLineParser.WindowsStyleSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WindowsStyleSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindowsStyleSwitch([NotNull] CommandLineParser.WindowsStyleSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WindowsStyleParameter</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindowsStyleParameter([NotNull] CommandLineParser.WindowsStyleParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WindowsStyleParameter</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindowsStyleParameter([NotNull] CommandLineParser.WindowsStyleParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnixStyleSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnixStyleSwitch([NotNull] CommandLineParser.UnixStyleSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnixStyleSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnixStyleSwitch([NotNull] CommandLineParser.UnixStyleSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnixStyleParameter</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnixStyleParameter([NotNull] CommandLineParser.UnixStyleParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnixStyleParameter</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnixStyleParameter([NotNull] CommandLineParser.UnixStyleParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnixStyleFlaggedSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnixStyleFlaggedSwitch([NotNull] CommandLineParser.UnixStyleFlaggedSwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnixStyleFlaggedSwitch</c>
	/// labeled alternative in <see cref="CommandLineParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnixStyleFlaggedSwitch([NotNull] CommandLineParser.UnixStyleFlaggedSwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] CommandLineParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] CommandLineParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] CommandLineParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] CommandLineParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Array</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] CommandLineParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Array</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] CommandLineParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] CommandLineParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] CommandLineParser.BooleanContext context);
}
} // namespace System.CommandLine.Parser.Antlr
