//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace System.CommandLine.Parser.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICommandLineListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
internal partial class CommandLineBaseListener : ICommandLineListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandLine([NotNull] CommandLineParser.CommandLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.commandLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandLine([NotNull] CommandLineParser.CommandLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.defaultParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultParameter([NotNull] CommandLineParser.DefaultParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.WindowsStyleSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindowsStyleSwitch([NotNull] CommandLineParser.WindowsStyleSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.WindowsStyleSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindowsStyleSwitch([NotNull] CommandLineParser.WindowsStyleSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.WindowsStyleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindowsStyleParameter([NotNull] CommandLineParser.WindowsStyleParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.WindowsStyleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindowsStyleParameter([NotNull] CommandLineParser.WindowsStyleParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.UnixStyleSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnixStyleSwitch([NotNull] CommandLineParser.UnixStyleSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.UnixStyleSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnixStyleSwitch([NotNull] CommandLineParser.UnixStyleSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.UnixStyleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnixStyleParameter([NotNull] CommandLineParser.UnixStyleParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.UnixStyleParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnixStyleParameter([NotNull] CommandLineParser.UnixStyleParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.UnixStyleFlaggedSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnixStyleFlaggedSwitch([NotNull] CommandLineParser.UnixStyleFlaggedSwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.UnixStyleFlaggedSwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnixStyleFlaggedSwitch([NotNull] CommandLineParser.UnixStyleFlaggedSwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.String"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] CommandLineParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.String"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] CommandLineParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.Number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] CommandLineParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.Number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] CommandLineParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.Array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] CommandLineParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.Array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] CommandLineParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.Boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] CommandLineParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.Boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] CommandLineParser.BooleanContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace System.CommandLine.Parser.Antlr
