<Project Sdk="Microsoft.NET.Sdk">
    <!-- Build Configuration -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CliNetCore</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <!-- Assembly Info -->
    <PropertyGroup>
        <AssemblyTitle>CLI.NET Core</AssemblyTitle>
        <Product>CLI.NET Core</Product>
        <NeutralLanguage>en-US</NeutralLanguage>
    </PropertyGroup>

    <!-- NuGet Package Information -->
    <PropertyGroup>
        <PackageId>CliNetCore</PackageId>
        <Version>0.1.0</Version>
        <title>CLI.NET Core</title>
        <Authors>David Neumann</Authors>
        <Description>A command line application framework in the style of ASP.NET Core.</Description>
        <Copyright>Copyright © 2026 David Neumann</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/lecode-official/command-line-parser/blob/master/source/clinet-core</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/lecode-official/command-line-parser</RepositoryUrl>
    </PropertyGroup>

    <!-- Referenced NuGet Packages -->
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    </ItemGroup>
</Project>
